### PR TITLE
feat: Configure namespaces

### LINKED ISSUE #4: config文件缺少namespace的配置
现在只能部署到default namespace下面，项目需要部署到不同的namespace

### PR DESCRIPTION
**Pull request by pmuens**
Closes #4 

Hey @yugasun I've just implemented support for configurable namespaces. Could you take a look at this PR and see if it fits into the Components design? I've added a unit test which passes but I'm not entirely sure if I've missed something.

Thanks in advance!

### CODE REVIEW

**Comment by yugasun** [comment]
That's great~

**Comment by anycodes** [comment]
Ok, thank you for this pr.
About the namespace of  SCF, we will weaken this function, so I need to check with the product manager to decide if I can merge.

**Comment by pmuens** [comment]
@yugasun thanks for reviewing :+1:

I just updated the code and did a global search for other usages of `'default'`. Furthermore I tested it manually and it seems to be working just fine.

**Comment by hjaimee** [comment]
> Ok, thank you for this pr.
> About the namespace of SCF, we will weaken this function, so I need to check with the product manager to decide if I can merge.

Does this mean you will be moving away from Namespaces for SCF? Has there been any updates on this? As we currently use namespaces to group similar or related SCFs?

**Pull request merged**
