### PR TITLE
feat: add dir support for include option

### PR DESCRIPTION
**Pull request by yugasun**

### CODE REVIEW

**Comment by yugasun** [comment]
@pmuens Yes, it was a bug for relative directory of `include`, I fixed it.

**Comment by yugasun** [comment]
@pmuens If you want include `include-me` folder in `xxx.zip` file，you should make `include-me` in your base code path which is specified by `codeUri`, otherwise `tencent-scf` will confused.

**Comment by pmuens** [comment]
Thanks for getting back @yugasun 

So the `include` option only includes the files in the given directory, but not the directory itself and if I want to include the whole directory I just have to move it into the directory which is referenced via `codeUri` and therefore I don't need `include`. Is that statement correct?

**Comment by yugasun** [comment]
> Thanks for getting back @yugasun
> 
> So the `include` option only includes the files in the given directory, but not the directory itself and if I want to include the whole directory I just have to move it into the directory which is referenced via `codeUri` and therefore I don't need `include`. Is that statement correct?

Definitely right.

**Pull request merged**
